trigger: none

parameters:
- name: arch
  type: string
  values:
  - amd64
  default: amd64

- name: pool
  type: string
  values:
  - sonicbld
  - default
  default: default

- name: timeout
  type: number
  default: 60

- name: sonic_slave
  type: string
  default: sonic-slave-bullseye:master

variables:
  - name: BUILD_BRANCH
    ${{ if eq(variables['Build.Reason'], 'PullRequest') }}:
      value: $(Build.SourceBranchName)
    ${{ else }}:
      value: $(Build.SourceBranchName)

schedules:
- cron: "0 0 * * *"
  displayName: Daily
  always: true
  branches:
    include:
    - master

jobs:
- job: build
  timeoutInMinutes: 240
  pool:
    vmImage: 'ubuntu-20.04'
  container:
    image: sonicdev-microsoft.azurecr.io:443/${{ parameters.sonic_slave }}:latest


  steps:
    - checkout: none
    - script: |
        sudo apt-get install gcc g++ libboost-dev cmake zlib1g-dev libsasl2-2

        git clone https://github.com/jbeder/yaml-cpp.git
        pushd yaml-cpp
        mkdir build
        pushd build
        cmake -DBUILD_SHARED_LIBS=OFF ..
        make
        sudo make install
        popd
        popd

        git clone https://github.com/edenhill/librdkafka.git
        pushd librdkafka
        ./configure
        make
        sudo make install
        popd

        git clone https://github.com/FengPan-Frank/openbmp
        pushd openbmp
        mkdir build
        pushd build
        cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ../
        make
        popd
        cat Server/CMakeFiles/openbmpd.dir/build.make
        cat Server/CMakeFiles/Makefile2
        popd
        sudo dpkg -l | grep libsasl2  
        sudo apt-get install libsasl2-dev  
        find / -name "libsasl2.so" -o -name "libsasl2.a" 2>/dev/null  
        sudo ldconfig  
    - publish: $(System.DefaultWorkingDirectory)/
      artifact: sonic-bmp.amd64.ubuntu20_04
      displayName: "Archive sonic-bmp packages"

